### ISSUE TITLE
password changed page style incorrect

### ISSUE THREAD

**Issue by j3ffml** [Full-House-UW/fullhouse#137]
If you change your password, the header on the page it redirects to is missing the logo button and has wierd alignment.

To reproduce, go to /accounts/password/change and submit a password change

**Comment by JSiu** [comment]
It looks like most of the pages related to auth have the wrong header/footer; my understanding is that this is because they extend registration_base.html, which overrides the header/footer from base.html.  If we delete the override, will it show with the correct look/feel? @creisman @snuriel92 @bkgomez, can one of you test this?  (And screw my effing VM in the meantime.)

**Comment by creisman** [comment]
#178

**Comment by natmote** [comment]
Has this been resolved?

**Comment by creisman** [comment]
I believe this was resolved in #178. I don't think I closed it because of the awkward position of accidentally merging myself.
