### ISSUE TITLE
Task description should be optional

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#171]

**Comment by bkgomez** [comment]
HTML5 has a 'date' input that lets users select a date from a calendar, which is what I was going to use originally. If we can get that working with the model then we won't have to worry about that. But it's just as easy to say type MM/DD/YYYY I suppose.

**Comment by JSiu** [comment]
Wherever we ask for a date, this should be specified (including on Announcement expiration).  Also, the displayed date is in the wrong format; when you save and come back to the page, it shows as YYYY-MM-DD.

**Comment by snuriel92** [comment]
I think we should jsut require it as YYYY-MM-DD for now (I got a lot of 'invalid dates' errors when I just created a task until I figured out the correct format)

**Comment by JSiu** [comment]
Sure, that works. Sounds like a good solution for this release.

**Comment by creisman** [comment]
I think there's some way to set which output format we want... But I don't know where. For this release I think it's fine to go with its default and we'll change it later if need be.

Brandon, the date field sounds lovely but I doubt IE8-IE9 will support it so that's out for now :(.

**Comment by JSiu** [comment]
Yeah, let's just change our labels for this release.  I think we need it in
three places: user settings (birthday), announcements (expiration date),
and tasks.

Janette Siu

---

Be more concerned with your character than your reputation, because your
character is what you really are, while your reputation is merely what
others think you are.
- Coach John Wooden, 1910-2010

**Comment by snuriel92** [comment]
oh, oops. I missed the announcements. I'll do that now.

**Comment by j3ffml** [comment]
closed by #212
