### ISSUE TITLE
decide on a user model, combination of user/member model

### ISSUE THREAD

**Issue by j3ffml** [Full-House-UW/fullhouse#41]
We can have a custom user that subclasses django's auth user model, or we can have a separate member model that has a one-to-one rel with an auth user. Other options may exist.

**Comment by cmoiceanu** [comment]
If we take the Django auth user model as is, do we still need to subclass?

**Comment by j3ffml** [comment]
Depends. If users will store what houses they are members of, then yes.

**Comment by cmoiceanu** [comment]
From the architecture model, the User class/models does not have 
references to anything (which I think it is the correct way).

Other models refer to userid (as to they need to know about a user). 
This is nice because it gives us the freedom to completely leverage any 
user model Django gives us unhindered.

**Comment by j3ffml** [comment]
Merged as #55
