### ISSUE TITLE
Welcome page text fields shift after inserting the wrong password.

### ISSUE THREAD

**Issue by cmoiceanu** [Full-House-UW/fullhouse#95]
From the welcome page – insert wrong password, text fields shift to right aligned rather than remain center aligned. 
See before try to login
 http://dl.dropbox.com/u/88614194/FullHouse_UI_Welcome_Login_001.PNG
See after entered wrong password
http://dl.dropbox.com/u/88614194/FullHouse_UI_Welcome_Login_002.PNG

**Comment by JSiu** [comment]
This is because the error message makes the width of the form bigger than it was before, and since the fields are right-aligned, they move right as the form expands. @creisman @snuriel92 @bkgomez, how do we want to fix it?

**Comment by creisman** [comment]
It's not as pronounced with the new error message, but it can be fixed by
wrapping the form fields in a div that doesn't include the error. This will
separate the lengthening of the error container from interfering with the
form fields size. This wrapper div may need margin:auto and/or a fixed
width. Do we want this in this release or punted to next?

**Comment by JSiu** [comment]
I think it should be in this release, because we mentioned it as an issue last release.

**Comment by creisman** [comment]
Alright, I'll have this fix posted in a second...

**Comment by creisman** [comment]
#175
